import * as comp from './api/companyAPI';
import * as exp from './api/expenseAPI';
import * as fin from './api/financeAPI';
import * as mark from './api/marketingAPI';
import * as proc from './api/procurementAPI';
import * as proj from './api/projectAPI';
import * as sal from './api/salesAPI';
import * as sch from './api/scheduleAPI';
import * as srv from './api/serviceAPI';
import * as sys from './api/systemAPI';
import * as tm from './api/timeAPI';
export declare class Connectwise {
    CompaniesApi: comp.CompaniesApi;
    CompanyManagementSummarysApi: comp.CompanyManagementSummarysApi;
    CompanyNotesApi: comp.CompanyNotesApi;
    CompanySitesApi: comp.CompanySitesApi;
    CompanyStatusesApi: comp.CompanyStatusesApi;
    CompanyTeamsApi: comp.CompanyTeamsApi;
    ConfigurationsApi: comp.ConfigurationsApi;
    ConfigurationStatusesApi: comp.ConfigurationStatusesApi;
    ConfigurationTypeQuestionsApi: comp.ConfigurationTypeQuestionsApi;
    ConfigurationTypesApi: comp.ConfigurationTypesApi;
    ContactCommunicationsApi: comp.ContactCommunicationsApi;
    ContactDepartmentsApi: comp.ContactDepartmentsApi;
    ContactNotesApi: comp.ContactNotesApi;
    ContactRelationshipsApi: comp.ContactRelationshipsApi;
    ContactsApi: comp.ContactsApi;
    ContactTypesApi: comp.ContactTypesApi;
    ExpenseEntriesApi: exp.ExpenseEntriesApi;
    ExpenseTypesApi: exp.ExpenseTypesApi;
    AgreementAdditionsApi: fin.AgreementAdditionsApi;
    AgreementAdjustmentsApi: fin.AgreementAdjustmentsApi;
    AgreementsApi: fin.AgreementsApi;
    AgreementSitesApi: fin.AgreementSitesApi;
    AgreementTypesApi: fin.AgreementTypesApi;
    AccountingBatchesApi: fin.AccountingBatchesApi;
    AgreementBoardDefaultsApi: fin.AgreementBoardDefaultsApi;
    InvoicePaymentsApi: fin.InvoicePaymentsApi;
    AccountingBatchTransactionsApi: fin.AccountingBatchTransactionsApi;
    AccountingUnpostedExpensesApi: fin.AccountingUnpostedExpensesApi;
    AccountingUnpostedInvoicesApi: fin.AccountingUnpostedinvoicesApi;
    AccountingUnpostedProcurementsApi: fin.AccountingUnpostedProcurementsApi;
    CampaignAuditsApi: mark.CampaignAuditsApi;
    CampaignsApi: mark.CampaignsApi;
    CampaignStatusesApi: mark.CampaignStatusesApi;
    CampaignTypesApi: mark.CampaignTypesApi;
    CampaignEmailsOpenedApi: mark.CampaignEmailsOpenedApi;
    CampaignFormsSubmittedApi: mark.CampaignFormsSubmittedApi;
    GroupsApi: mark.GroupsApi;
    CampaignLinksClickedApi: mark.CampaignLinksClickedApi;
    GroupCompaniesApi: mark.GroupCompaniesApi;
    GroupContactsApi: mark.GroupContactsApi;
    CatalogComponentsApi: proc.CatalogComponentsApi;
    CatalogsItemApi: proc.CatalogsItemApi;
    ManufacturersApi: proc.ManufacturersApi;
    ProductComponentsApi: proc.ProductComponentsApi;
    ProductPickingShippingDetailsApi: proc.ProductPickingShippingDetailsApi;
    ProductsItemApi: proc.ProductsItemApi;
    PurchaseOrdersApi: proc.PurchaseOrdersApi;
    ProjectContactsApi: proj.ProjectContactsApi;
    ProjectNotesApi: proj.ProjectNotesApi;
    ProjectPhasesApi: proj.ProjectPhasesApi;
    ProjectsApi: proj.ProjectsApi;
    ProjectsTeamMembersApi: proj.ProjectsTeamMembersApi;
    ActivitiesApi: sal.ActivitiesApi;
    ActivitiesStatusesApi: sal.ActivityStatusesApi;
    OpportunityForecastsApi: sal.OpportunityForecastsApi;
    OpportunitiesApi: sal.OpportunitiesApi;
    OpportunityContactsApi: sal.OpportunityContactsApi;
    OpportunityNotesApi: sal.OpportunityNotesApi;
    OpportunityRatingsApi: sal.OpportunityRatingsApi;
    OpportunityStatusesApi: sal.OpportunityStatusesApi;
    OpportunityTeamsApi: sal.OpportunityTeamsApi;
    OpportunityTypesApi: sal.OpportunityTypesApi;
    OrdersApi: sal.OrdersApi;
    ScheduleEntriesApi: sch.ScheduleEntriesApi;
    ScheduleStatuesApi: sch.ScheduleStatusesApi;
    ScheduleTypesApi: sch.ScheduleTypesApi;
    BoardsApi: srv.BoardsApi;
    CodesApi: srv.CodesApi;
    BoardExcludedMembersApi: srv.BoardExcludedMembersApi;
    BoardItemsApi: srv.BoardItemsApi;
    KnowledgeBaseArticlesApi: srv.KnowledgeBaseArticlesApi;
    LocationsApi: srv.LocationsApi;
    PrioritiesApi: srv.PrioritiesApi;
    TicketNotesApi: srv.TicketNotesApi;
    SourcesApi: srv.SourcesApi;
    BoardStatusesApi: srv.BoardStatusesApi;
    BoardSubTypesApi: srv.BoardSubTypesApi;
    SurveyQuestionsApi: srv.SurveyQuestionsApi;
    SurveyResultsApi: srv.SurveyResultsApi;
    SurveysApi: srv.SurveysApi;
    TicketTasksApi: srv.TicketTasksApi;
    BoardTeamsApi: srv.BoardTeamsApi;
    TicketsApi: srv.TicketsApi;
    BoardTypesApi: srv.BoardTypesApi;
    AuditTrailApi: sys.AuditTrailApi;
    CallbackEntriesApi: sys.CallbackEntriesApi;
    ConnectWiseHostedSetupsApi: sys.ConnectWiseHostedSetupsApi;
    DocumentsApi: sys.DocumentsApi;
    InfoApi: sys.InfoApi;
    IntegrationsApi: sys.IntegrationsApi;
    LinksApi: sys.LinksApi;
    MembersApi: sys.MembersApi;
    MenuEntriesApi: sys.MenuEntriesApi;
    ReportsApi: sys.ReportsApi;
    UserDefinedFieldsApi: sys.UserDefinedFieldsApi;
    TimeEntriesApi: tm.TimeEntriesApi;
    private authKey;
    constructor(host: string, companyId: string, publicKey: string, privateKey: string);
}
